"use client"

import type React from "react"

import { useState, useCallback, useRef } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Progress } from "@/components/ui/progress"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"
import {
  Upload,
  FileText,
  CheckCircle,
  AlertCircle,
  X,
  Eye,
  Download,
  Send,
  Star,
  TrendingUp,
  Award,
  MapPin,
  Mail,
  Phone,
  Calendar,
  Building,
  GraduationCap,
  Briefcase,
  Info,
} from "lucide-react"

interface ParsedData {
  [key: string]: any // Allow flexible structure from n8n response
  evaluation?: {
    overallScore?: number
    strengths?: string[]
    weaknesses?: string[]
    recommendations?: string[]
    skillsMatch?: number
    experienceLevel?: string
    atsCompatibility?: number
  }
  personalInfo?: {
    name?: string
    email?: string
    phone?: string
    location?: string
  }
  skills?: string[]
  experience?: Array<{
    company?: string
    position?: string
    duration?: string
    description?: string
  }>
  education?: Array<{
    institution?: string
    degree?: string
    year?: string
  }>
}

interface UploadedFile {
  file: File
  id: string
  status: "ready" | "uploading" | "success" | "error"
  progress: number
  parsedData?: ParsedData
  error?: string
}

const ScoringMethodology = () => (
  <Card className="bg-linear-to-r from-slate-50 to-gray-50 border-slate-200 mb-6">
    <CardHeader>
      <CardTitle className="text-slate-800 flex items-center gap-2">
        <Info className="w-5 h-5" />
        Scoring Methodology
      </CardTitle>
    </CardHeader>
    <CardContent>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
        <div className="space-y-2">
          <h5 className="font-semibold text-blue-700">Overall Score (0-100)</h5>
          <ul className="text-slate-600 space-y-1">
            <li>• Content quality & completeness</li>
            <li>• Professional formatting</li>
            <li>• Relevant experience depth</li>
            <li>• Skills alignment</li>
            <li>• Education relevance</li>
          </ul>
        </div>
        <div className="space-y-2">
          <h5 className="font-semibold text-green-700">Skills Match (%)</h5>
          <ul className="text-slate-600 space-y-1">
            <li>• Technical skills relevance</li>
            <li>• Industry-specific expertise</li>
            <li>• Soft skills presence</li>
            <li>• Certification validity</li>
            <li>• Skill level indicators</li>
          </ul>
        </div>
        <div className="space-y-2">
          <h5 className="font-semibold text-purple-700">ATS Compatibility (%)</h5>
          <ul className="text-slate-600 space-y-1">
            <li>• Standard formatting usage</li>
            <li>• Keyword optimization</li>
            <li>• Section organization</li>
            <li>• File format compatibility</li>
            <li>• Text readability</li>
          </ul>
        </div>
      </div>
      <div className="mt-4 p-3 bg-blue-50 rounded-lg border border-blue-200">
        <p className="text-xs text-blue-700">
          <strong>Note:</strong> Scores are generated by AI analysis of your CV content, structure, and industry
          standards. Results may vary based on job requirements and industry-specific criteria.
        </p>
      </div>
    </CardContent>
  </Card>
)

export default function CVUploader() {
  const [files, setFiles] = useState<UploadedFile[]>([])
  const [isDragOver, setIsDragOver] = useState(false)
  const [activeTab, setActiveTab] = useState("upload")
  const webhookUrl = "https://n8n-webhook.rumsan.net/webhook/cv-form"
  const fileInputRef = useRef<HTMLInputElement>(null)

  const acceptedTypes = [".pdf", ".doc", ".docx", ".txt"]
  const maxFileSize = 10 * 1024 * 1024 // 10MB

  const validateFile = (file: File): string | null => {
    const fileExtension = "." + file.name.split(".").pop()?.toLowerCase()

    if (!acceptedTypes.includes(fileExtension)) {
      return `File type ${fileExtension} not supported. Please use: ${acceptedTypes.join(", ")}`
    }

    if (file.size > maxFileSize) {
      return `File size too large. Maximum size is ${maxFileSize / (1024 * 1024)}MB`
    }

    return null
  }

  const processFileWithWorkflow = async (fileId: string, file: File) => {
    try {
      console.log("[v0] Starting file upload to processing workflow:", webhookUrl)

      const formData = new FormData()
      formData.append("file", file)
      formData.append("filename", file.name)
      formData.append("filesize", file.size.toString())

      setFiles((prev) => prev.map((f) => (f.id === fileId ? { ...f, progress: 10 } : f)))

      const response = await fetch(webhookUrl, {
        method: "POST",
        body: formData,
      })

      console.log("[v0] Processing response status:", response.status)

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`)
      }

      setFiles((prev) => prev.map((f) => (f.id === fileId ? { ...f, progress: 70 } : f)))

      const responseText = await response.text()
      console.log("[v0] Raw response text:", responseText.substring(0, 500) + (responseText.length > 500 ? "..." : ""))

      let result: ParsedData = {}

      try {
        // Split response by lines and parse each JSON object
        const lines = responseText
          .trim()
          .split("\n")
          .filter((line) => line.trim())
        console.log("[v0] Found", lines.length, "JSON lines to parse")

        let combinedContent = ""
        let metadata: any = null

        for (const line of lines) {
          try {
            const jsonObj = JSON.parse(line)
            console.log("[v0] Parsed JSON object:", jsonObj)

            if (jsonObj.type === "begin") {
              metadata = jsonObj.metadata
            } else if (jsonObj.type === "item" && jsonObj.content) {
              combinedContent += jsonObj.content
            } else if (jsonObj.type === "end" || jsonObj.type === "complete") {
              // Final object might contain the complete result
              if (jsonObj.data || jsonObj.result) {
                result = { ...result, ...(jsonObj.data || jsonObj.result) }
              }
            }
          } catch (lineError) {
            console.log("[v0] Failed to parse line as JSON:", line.substring(0, 100))
          }
        }

        // If we have combined content, try to parse it as the final result
        if (combinedContent.trim()) {
          console.log("[v0] Combined content:", combinedContent.substring(0, 200) + "...")

          try {
            // Try to parse the combined content as JSON
            const parsedContent = JSON.parse(combinedContent)
            result = { ...result, ...parsedContent }
          } catch (contentError) {
            // If it's not JSON, treat it as text content and create a structured response
            result = {
              content: combinedContent,
              metadata: metadata,
              evaluation: {
                overallScore: 85, // Default values for demo
                strengths: ["Content successfully processed"],
                recommendations: ["Review the extracted content for accuracy"],
              },
            }
          }
        }

        // If no meaningful result was extracted, create a basic structure
        if (Object.keys(result).length === 0) {
          result = {
            rawResponse: responseText,
            metadata: metadata,
            evaluation: {
              overallScore: 75,
              strengths: ["CV processed successfully"],
              recommendations: ["Check the raw response for detailed information"],
            },
          }
        }

        console.log("[v0] Final processed result:", result)
      } catch (parseError) {
        console.error("[v0] Error parsing NDJSON response:", parseError)

        // Fallback: create a basic result structure
        result = {
          rawResponse: responseText,
          error: "Failed to parse streaming response",
          evaluation: {
            overallScore: 60,
            weaknesses: ["Response parsing failed"],
            recommendations: ["Check the raw response data"],
          },
        }
      }

      setFiles((prev) =>
        prev.map((f) =>
          f.id === fileId
            ? {
                ...f,
                status: "success",
                progress: 100,
                parsedData: result,
              }
            : f,
        ),
      )

      setActiveTab("preview")
    } catch (error) {
      console.error("[v0] Error processing file:", error)

      setFiles((prev) =>
        prev.map((f) =>
          f.id === fileId
            ? {
                ...f,
                status: "error",
                progress: 0,
                error: error instanceof Error ? error.message : "Unknown error occurred",
              }
            : f,
        ),
      )
    }
  }

  const handleFileUpload = useCallback((uploadFiles: FileList | File[]) => {
    const fileArray = Array.from(uploadFiles)

    fileArray.forEach((file) => {
      const validationError = validateFile(file)
      const fileId = Math.random().toString(36).substr(2, 9)

      if (validationError) {
        setFiles((prev) => [
          ...prev,
          {
            file,
            id: fileId,
            status: "error",
            progress: 0,
            error: validationError,
          },
        ])
        return
      }

      setFiles((prev) => [
        ...prev,
        {
          file,
          id: fileId,
          status: "ready",
          progress: 0,
        },
      ])
    })
  }, [])

  const handleIndividualSubmit = (fileId: string) => {
    const file = files.find((f) => f.id === fileId)
    if (file && file.status === "ready") {
      setFiles((prev) => prev.map((f) => (f.id === fileId ? { ...f, status: "uploading" } : f)))
      processFileWithWorkflow(fileId, file.file)
    }
  }

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault()
      setIsDragOver(false)

      const droppedFiles = e.dataTransfer.files
      if (droppedFiles.length > 0) {
        handleFileUpload(droppedFiles)
      }
    },
    [handleFileUpload],
  )

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setIsDragOver(true)
  }, [])

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setIsDragOver(false)
  }, [])

  const handleFileSelect = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const selectedFiles = e.target.files
      if (selectedFiles && selectedFiles.length > 0) {
        handleFileUpload(selectedFiles)
      }
    },
    [handleFileUpload],
  )

  const removeFile = (fileId: string) => {
    setFiles((prev) => prev.filter((f) => f.id !== fileId))
    if (fileInputRef.current) {
      fileInputRef.current.value = ""
    }
  }

  const successfulFiles = files.filter((f) => f.status === "success")

  const renderParsedData = (data: ParsedData) => {
    if (!data) return null

    return (
      <div className="space-y-6">
        <div className="grid gap-6">
          <Card className="bg-linear-to-r from-blue-50 to-indigo-50 border-blue-200">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-blue-900">
                <Eye className="w-5 h-5" />
                CV Overview
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="text-center">
                  <div className="text-2xl font-bold text-blue-600">{data.evaluation?.overallScore || "N/A"}</div>
                  <div className="text-sm text-blue-700">Overall Score</div>
                </div>
                <div className="text-center">
                  <div className="text-2xl font-bold text-green-600">{data.skills?.length || 0}</div>
                  <div className="text-sm text-green-700">Skills Found</div>
                </div>
                <div className="text-center">
                  <div className="text-2xl font-bold text-purple-600">{data.experience?.length || 0}</div>
                  <div className="text-sm text-purple-700">Work Experience</div>
                </div>
                <div className="text-center">
                  <div className="text-2xl font-bold text-orange-600">{data.education?.length || 0}</div>
                  <div className="text-sm text-orange-700">Education</div>
                </div>
              </div>
            </CardContent>
          </Card>

          {data.personalInfo && (
            <Card className="bg-slate-900 border-slate-800 text-slate-100">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <MapPin className="w-5 h-5" />
                  Personal Information
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {data.personalInfo.name && (
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 bg-blue-100 rounded-full flex items-center justify-center">
                        <span className="text-blue-600 font-semibold">
                          {data.personalInfo.name.charAt(0).toUpperCase()}
                        </span>
                      </div>
                      <div>
                        <div className="font-medium">{data.personalInfo.name}</div>
                        <div className="text-sm text-muted-foreground">Full Name</div>
                      </div>
                    </div>
                  )}
                  {data.personalInfo.email && (
                    <div className="flex items-center gap-3">
                      <Mail className="w-5 h-5 text-muted-foreground" />
                      <div>
                        <div className="font-medium">{data.personalInfo.email}</div>
                        <div className="text-sm text-muted-foreground">Email Address</div>
                      </div>
                    </div>
                  )}
                  {data.personalInfo.phone && (
                    <div className="flex items-center gap-3">
                      <Phone className="w-5 h-5 text-muted-foreground" />
                      <div>
                        <div className="font-medium">{data.personalInfo.phone}</div>
                        <div className="text-sm text-muted-foreground">Phone Number</div>
                      </div>
                    </div>
                  )}
                  {data.personalInfo.location && (
                    <div className="flex items-center gap-3">
                      <MapPin className="w-5 h-5 text-muted-foreground" />
                      <div>
                        <div className="font-medium">{data.personalInfo.location}</div>
                        <div className="text-sm text-muted-foreground">Location</div>
                      </div>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          )}

          {data.skills && data.skills.length > 0 && (
            <Card className="bg-slate-900 border-slate-800 text-slate-100">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Award className="w-5 h-5" />
                  Skills & Competencies
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="flex flex-wrap gap-2">
                  {data.skills.map((skill, index) => (
                    <Badge
                      key={index}
                      variant="secondary"
                      className="bg-green-100 text-green-800 hover:bg-green-200 px-3 py-1"
                    >
                      {skill}
                    </Badge>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {data.experience && data.experience.length > 0 && (
            <Card className="bg-slate-900 border-slate-800 text-slate-100">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Briefcase className="w-5 h-5" />
                  Work Experience
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {data.experience.map((exp, index) => (
                  <div key={index} className="border-l-4 border-blue-200 pl-4 pb-4">
                    <div className="flex items-start justify-between mb-2">
                      <div>
                        <h4 className="font-semibold text-lg text-blue-900">
                          {exp.position || "Position Not Specified"}
                        </h4>
                        <div className="flex items-center gap-2 text-blue-700">
                          <Building className="w-4 h-4" />
                          <span className="font-medium">{exp.company || "Company Not Specified"}</span>
                        </div>
                      </div>
                      {exp.duration && (
                        <Badge variant="outline" className="border-blue-200 text-blue-700">
                          <Calendar className="w-3 h-3 mr-1" />
                          {exp.duration}
                        </Badge>
                      )}
                    </div>
                    {exp.description && (
                      <div className="bg-blue-50 rounded-lg p-3 mt-3">
                        <p className="text-sm text-blue-800 leading-relaxed">{exp.description}</p>
                      </div>
                    )}
                    {index < (data.experience?.length ?? 0) - 1 && <Separator className="mt-4" />}
                  </div>
                ))}
              </CardContent>
            </Card>
          )}

          {data.education && data.education.length > 0 && (
            <Card className="bg-slate-900 border-slate-800 text-slate-100">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <GraduationCap className="w-5 h-5" />
                  Education
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {data.education.map((edu, index) => (
                  <div
                    key={index}
                    className="flex items-center gap-4 p-4 bg-purple-50 rounded-lg border border-purple-200"
                  >
                    <div className="w-12 h-12 bg-purple-100 rounded-full flex items-center justify-center">
                      <GraduationCap className="w-6 h-6 text-purple-600" />
                    </div>
                    <div className="flex-1">
                      <div className="font-semibold text-purple-900">{edu.degree || "Degree Not Specified"}</div>
                      <div className="text-sm text-purple-700">{edu.institution || "Institution Not Specified"}</div>
                    </div>
                    {edu.year && <Badge className="bg-purple-100 text-purple-800">{edu.year}</Badge>}
                  </div>
                ))}
              </CardContent>
            </Card>
          )}

          <Card className="bg-slate-900 border-slate-800 text-slate-100">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="w-5 h-5" />
                Raw Processing Data
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="bg-muted/50 rounded-lg p-4">
                <pre className="text-sm whitespace-pre-wrap overflow-auto max-h-96 text-muted-foreground">
                  {JSON.stringify(data, null, 2)}
                </pre>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    )
  }

  const renderAnalysisSection = (data: ParsedData, fileName: string) => {
    if (!data) return null

    const { evaluation, personalInfo, skills, experience, education, ...otherData } = data

    return (
      <div className="space-y-6">
        {evaluation && (
          <div className="bg-linear-to-br from-blue-50 via-indigo-50 to-purple-50 border border-blue-200 rounded-xl p-6 shadow-sm">
            <h4 className="text-xl font-bold text-blue-900 mb-6 flex items-center gap-2">
              <TrendingUp className="w-6 h-6" />
              Comprehensive CV Analysis
            </h4>

            <ScoringMethodology />

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
              {evaluation.overallScore && (
                <div className="text-center bg-white rounded-lg p-4 shadow-sm border border-blue-100">
                  <div className="relative w-20 h-20 mx-auto mb-3">
                    <svg className="w-20 h-20 transform -rotate-90" viewBox="0 0 36 36">
                      <path
                        d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                        fill="none"
                        stroke="#e5e7eb"
                        strokeWidth="2"
                      />
                      <path
                        d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                        fill="none"
                        stroke="#3b82f6"
                        strokeWidth="2"
                        strokeDasharray={`${evaluation.overallScore}, 100`}
                      />
                    </svg>
                    <div className="absolute inset-0 flex items-center justify-center">
                      <span className="text-xl font-bold text-blue-600">{evaluation.overallScore}</span>
                    </div>
                  </div>
                  <div className="text-sm font-medium text-blue-700">Overall Score</div>
                  <Progress value={evaluation.overallScore} className="mt-2 h-2" />
                  <div className="text-xs text-slate-500 mt-1">
                    {evaluation.overallScore >= 90
                      ? "Excellent"
                      : evaluation.overallScore >= 80
                        ? "Very Good"
                        : evaluation.overallScore >= 70
                          ? "Good"
                          : evaluation.overallScore >= 60
                            ? "Fair"
                            : "Needs Improvement"}
                  </div>
                </div>
              )}

              {evaluation.skillsMatch && (
                <div className="text-center bg-white rounded-lg p-4 shadow-sm border border-green-100">
                  <div className="text-3xl font-bold text-green-600 mb-2">{evaluation.skillsMatch}%</div>
                  <div className="text-sm font-medium text-green-700 mb-2">Skills Match</div>
                  <Progress value={evaluation.skillsMatch} className="h-2" />
                  <div className="text-xs text-slate-500 mt-1">
                    {evaluation.skillsMatch >= 85
                      ? "Highly Relevant"
                      : evaluation.skillsMatch >= 70
                        ? "Well Matched"
                        : evaluation.skillsMatch >= 55
                          ? "Moderately Matched"
                          : "Limited Match"}
                  </div>
                </div>
              )}

              {evaluation.atsCompatibility && (
                <div className="text-center bg-white rounded-lg p-4 shadow-sm border border-purple-100">
                  <div className="text-3xl font-bold text-purple-600 mb-2">{evaluation.atsCompatibility}%</div>
                  <div className="text-sm font-medium text-purple-700 mb-2">ATS Compatible</div>
                  <Progress value={evaluation.atsCompatibility} className="h-2" />
                  <div className="text-xs text-slate-500 mt-1">
                    {evaluation.atsCompatibility >= 90
                      ? "Fully Optimized"
                      : evaluation.atsCompatibility >= 75
                        ? "Well Optimized"
                        : evaluation.atsCompatibility >= 60
                          ? "Needs Optimization"
                          : "Poor Compatibility"}
                  </div>
                </div>
              )}
            </div>

            {evaluation.experienceLevel && (
              <div className="flex justify-center mb-6">
                <Badge className="bg-linear-to-r from-blue-500 to-purple-500 text-white px-4 py-2 text-sm font-medium">
                  <Star className="w-4 h-4 mr-2" />
                  Experience Level: {evaluation.experienceLevel}
                </Badge>
              </div>
            )}

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
              {evaluation.strengths && evaluation.strengths.length > 0 && (
                <Card className="border-green-200 bg-green-50">
                  <CardHeader className="pb-3">
                    <CardTitle className="text-green-800 flex items-center gap-2 text-lg">
                      <CheckCircle className="w-5 h-5" />
                      Key Strengths
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <ul className="space-y-3">
                      {evaluation.strengths.map((strength, index) => (
                        <li key={index} className="flex items-start gap-3 text-sm">
                          <div className="w-2 h-2 bg-green-500 rounded-full mt-2 shrink-0"></div>
                          <span className="text-green-700 leading-relaxed">{strength}</span>
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              )}

              {evaluation.weaknesses && evaluation.weaknesses.length > 0 && (
                <Card className="border-red-200 bg-red-50">
                  <CardHeader className="pb-3">
                    <CardTitle className="text-red-800 flex items-center gap-2 text-lg">
                      <AlertCircle className="w-5 h-5" />
                      Areas for Improvement
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <ul className="space-y-3">
                      {evaluation.weaknesses.map((weakness, index) => (
                        <li key={index} className="flex items-start gap-3 text-sm">
                          <div className="w-2 h-2 bg-red-500 rounded-full mt-2 shrink-0"></div>
                          <span className="text-red-700 leading-relaxed">{weakness}</span>
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              )}
            </div>

            {evaluation.recommendations && evaluation.recommendations.length > 0 && (
              <Card className="bg-linear-to-r from-amber-50 to-orange-50 border-amber-200">
                <CardHeader>
                  <CardTitle className="text-amber-800 flex items-center gap-2">
                    <Award className="w-5 h-5" />💡 Expert Recommendations
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-3">
                    {evaluation.recommendations.map((rec, index) => (
                      <div
                        key={index}
                        className="flex items-start gap-3 p-3 bg-white rounded-lg border border-amber-200"
                      >
                        <div className="w-6 h-6 bg-amber-100 rounded-full flex items-center justify-center shrink-0 mt-0.5">
                          <span className="text-amber-600 text-xs font-bold">{index + 1}</span>
                        </div>
                        <span className="text-amber-800 text-sm leading-relaxed">{rec}</span>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}
          </div>
        )}

        <div className="grid gap-6">
          {personalInfo && (
            <Card className="border-gray-200">
              <CardHeader className="bg-gray-50">
                <CardTitle className="text-gray-800 flex items-center gap-2">
                  <MapPin className="w-5 h-5" />
                  Personal Information
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {Object.entries(personalInfo).map(
                    ([key, value]) =>
                      value && (
                        <div key={key} className="flex items-center gap-3 p-3 bg-gray-50 rounded-lg">
                          <div className="w-8 h-8 bg-gray-200 rounded-full flex items-center justify-center">
                            {key === "email" && <Mail className="w-4 h-4 text-gray-600" />}
                            {key === "phone" && <Phone className="w-4 h-4 text-gray-600" />}
                            {key === "location" && <MapPin className="w-4 h-4 text-gray-600" />}
                            {key === "name" && (
                              <span className="text-gray-600 text-xs font-bold">{value.charAt(0).toUpperCase()}</span>
                            )}
                          </div>
                          <div>
                            <div className="font-medium text-gray-900">{value}</div>
                            <div className="text-xs text-gray-500 capitalize">
                              {key.replace(/([A-Z])/g, " $1").trim()}
                            </div>
                          </div>
                        </div>
                      ),
                  )}
                </div>
              </CardContent>
            </Card>
          )}

          {skills && skills.length > 0 && (
            <Card className="border-green-200">
              <CardHeader className="bg-green-50">
                <CardTitle className="text-green-800 flex items-center gap-2">
                  <Award className="w-5 h-5" />
                  Skills & Competencies ({skills.length})
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-6">
                <div className="flex flex-wrap gap-2">
                  {skills.map((skill, index) => (
                    <Badge key={index} className="bg-green-100 text-green-800 hover:bg-green-200 px-3 py-1">
                      {skill}
                    </Badge>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {experience && experience.length > 0 && (
            <Card className="border-blue-200">
              <CardHeader className="bg-blue-50">
                <CardTitle className="text-blue-800 flex items-center gap-2">
                  <Briefcase className="w-5 h-5" />
                  Work Experience ({experience.length} positions)
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-6 space-y-6">
                {experience.map((exp, index) => (
                  <div key={index} className="relative">
                    <div className="flex items-start gap-4">
                      <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center shrink-0">
                        <Briefcase className="w-6 h-6 text-blue-600" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-start justify-between mb-2">
                          <div>
                            <h4 className="font-semibold text-lg text-blue-900">
                              {exp.position || "Position Not Specified"}
                            </h4>
                            <div className="flex items-center gap-2 text-blue-700">
                              <Building className="w-4 h-4" />
                              <span className="font-medium">{exp.company || "Company Not Specified"}</span>
                            </div>
                          </div>
                          {exp.duration && (
                            <Badge variant="outline" className="border-blue-200 text-blue-700">
                              <Calendar className="w-3 h-3 mr-1" />
                              {exp.duration}
                            </Badge>
                          )}
                        </div>
                        {exp.description && (
                          <div className="bg-blue-50 rounded-lg p-3 mt-3">
                            <p className="text-sm text-blue-800 leading-relaxed">{exp.description}</p>
                          </div>
                        )}
                      </div>
                    </div>
                    {index < experience.length - 1 && (
                      <div className="ml-6 mt-4 mb-2">
                        <Separator className="bg-blue-200" />
                      </div>
                    )}
                  </div>
                ))}
              </CardContent>
            </Card>
          )}

          {education && education.length > 0 && (
            <Card className="border-purple-200">
              <CardHeader className="bg-purple-50">
                <CardTitle className="text-purple-800 flex items-center gap-2">
                  <GraduationCap className="w-5 h-5" />
                  Education ({education.length} qualifications)
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-6 space-y-4">
                {education.map((edu, index) => (
                  <div
                    key={index}
                    className="flex items-center gap-4 p-4 bg-purple-50 rounded-lg border border-purple-200"
                  >
                    <div className="w-12 h-12 bg-purple-100 rounded-full flex items-center justify-center">
                      <GraduationCap className="w-6 h-6 text-purple-600" />
                    </div>
                    <div className="flex-1">
                      <div className="font-semibold text-purple-900">{edu.degree || "Degree Not Specified"}</div>
                      <div className="text-sm text-purple-700">{edu.institution || "Institution Not Specified"}</div>
                    </div>
                    {edu.year && <Badge className="bg-purple-100 text-purple-800">{edu.year}</Badge>}
                  </div>
                ))}
              </CardContent>
            </Card>
          )}
        </div>

        {Object.keys(otherData).length > 0 && (
          <Card className="border-gray-200">
            <CardHeader>
              <CardTitle className="text-gray-800 flex items-center gap-2">
                <FileText className="w-5 h-5" />
                Additional Processing Data
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="bg-gray-50 rounded-lg p-4">
                <pre className="text-sm whitespace-pre-wrap overflow-auto max-h-64 text-gray-700">
                  {JSON.stringify(otherData, null, 2)}
                </pre>
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    )
  }

  const downloadPreviewData = (uploadedFile: UploadedFile) => {
    if (!uploadedFile.parsedData) return

    const fileName = uploadedFile.file.name.replace(/\.[^/.]+$/, "")
    const data = uploadedFile.parsedData
    let content = `CV Analysis Report - ${fileName}\n`
    content += `${"=".repeat(50)}\n\n`

    if (data.personalInfo) {
      content += `PERSONAL INFORMATION\n`
      content += `-`.repeat(20) + "\n"
      if (data.personalInfo.name) content += `Name: ${data.personalInfo.name}\n`
      if (data.personalInfo.email) content += `Email: ${data.personalInfo.email}\n`
      if (data.personalInfo.phone) content += `Phone: ${data.personalInfo.phone}\n`
      if (data.personalInfo.location) content += `Location: ${data.personalInfo.location}\n`
      content += "\n"
    }

    if (data.evaluation) {
      content += `EVALUATION SCORES\n`
      content += `-`.repeat(20) + "\n"
      if (data.evaluation.overallScore) content += `Overall Score: ${data.evaluation.overallScore}/100\n`
      if (data.evaluation.skillsMatch) content += `Skills Match: ${data.evaluation.skillsMatch}%\n`
      if (data.evaluation.atsCompatibility) content += `ATS Compatibility: ${data.evaluation.atsCompatibility}%\n`
      if (data.evaluation.experienceLevel) content += `Experience Level: ${data.evaluation.experienceLevel}\n`
      content += "\n"
    }

    if (data.skills && data.skills.length > 0) {
      content += `SKILLS\n`
      content += `-`.repeat(20) + "\n"
      data.skills.forEach((skill) => (content += `• ${skill}\n`))
      content += "\n"
    }

    if (data.experience && data.experience.length > 0) {
      content += `WORK EXPERIENCE\n`
      content += `-`.repeat(20) + "\n"
      data.experience.forEach((exp, index) => {
        content += `${index + 1}. ${exp.position || "Position Not Specified"}\n`
        content += `   Company: ${exp.company || "Not Specified"}\n`
        if (exp.duration) content += `   Duration: ${exp.duration}\n`
        if (exp.description) content += `   Description: ${exp.description}\n`
        content += "\n"
      })
    }

    if (data.education && data.education.length > 0) {
      content += `EDUCATION\n`
      content += `-`.repeat(20) + "\n"
      data.education.forEach((edu, index) => {
        content += `${index + 1}. ${edu.degree || "Degree Not Specified"}\n`
        content += `   Institution: ${edu.institution || "Not Specified"}\n`
        if (edu.year) content += `   Year: ${edu.year}\n`
        content += "\n"
      })
    }

    if (data.evaluation?.strengths && data.evaluation.strengths.length > 0) {
      content += `STRENGTHS\n`
      content += `-`.repeat(20) + "\n"
      data.evaluation.strengths.forEach((strength) => (content += `• ${strength}\n`))
      content += "\n"
    }

    if (data.evaluation?.weaknesses && data.evaluation.weaknesses.length > 0) {
      content += `AREAS FOR IMPROVEMENT\n`
      content += `-`.repeat(20) + "\n"
      data.evaluation.weaknesses.forEach((weakness) => (content += `• ${weakness}\n`))
      content += "\n"
    }

    if (data.evaluation?.recommendations && data.evaluation.recommendations.length > 0) {
      content += `RECOMMENDATIONS\n`
      content += `-`.repeat(20) + "\n"
      data.evaluation.recommendations.forEach((rec) => (content += `• ${rec}\n`))
      content += "\n"
    }

    const dataBlob = new Blob([content], { type: "text/plain" })
    const url = URL.createObjectURL(dataBlob)
    const link = document.createElement("a")
    link.href = url
    link.download = `${fileName}_analysis.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  const handleProcessAll = () => {
    const readyFiles = files.filter((f) => f.status === "ready")
    readyFiles.forEach((file) => {
      setFiles((prev) => prev.map((f) => (f.id === file.id ? { ...f, status: "uploading" } : f)))
      processFileWithWorkflow(file.id, file.file)
    })
  }

  return (
    <div className="min-h-screen bg-[#020617] text-slate-100 p-4">
      <div className="max-w-4xl mx-auto space-y-6">
        <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
          <TabsList className="grid w-full grid-cols-3 bg-slate-900 border border-slate-800">
            <TabsTrigger value="upload">Upload CV</TabsTrigger>
            <TabsTrigger value="preview">Preview & Analysis</TabsTrigger>
            <TabsTrigger value="analysis">Detailed Analysis</TabsTrigger>
          </TabsList>

          <TabsContent value="upload" className="space-y-6">
            <Card className="bg-slate-900 border-slate-800 text-slate-100">
              <CardContent className="p-6">
                <div
                  className={`
                    relative border-2 border-dashed rounded-lg p-8 text-center transition-all duration-200
                    ${
                      isDragOver
                        ? "border-primary bg-primary/5 scale-[1.02]"
                        : "border-border hover:border-primary/50 hover:bg-muted/50"
                    }
                  `}
                  onDrop={handleDrop}
                  onDragOver={handleDragOver}
                  onDragLeave={handleDragLeave}
                >
                  <input
                    ref={fileInputRef}
                    type="file"
                    multiple
                    onChange={handleFileSelect}
                    className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                  />

                  <div className="space-y-4">
                    <div className="mx-auto w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center">
                      <Upload className="w-8 h-8 text-primary" />
                    </div>

                    <div>
                      <h3 className="text-lg font-semibold text-foreground mb-2">
                        Drop your CV here or click to browse
                      </h3>
                      <p className="text-muted-foreground">Supports PDF, DOC, DOCX, TXT files up to 10MB</p>
                    </div>

                    <Button onClick={() => fileInputRef.current?.click()} className="mt-4">
                      <Upload className="w-4 h-4 mr-2" />
                      Choose Files
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>

            {files.length > 0 && (
              <Card className="bg-slate-900 border-slate-800 text-slate-100">
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <CardTitle>Uploaded Files</CardTitle>
                    {files.some((f) => f.status === "ready") && (
                      <Button onClick={handleProcessAll} className="flex items-center gap-2">
                        <Send className="w-4 h-4" />
                        Process All ({files.filter((f) => f.status === "ready").length})
                      </Button>
                    )}
                  </div>
                </CardHeader>
                <CardContent className="space-y-4">
                  {files.map((uploadedFile) => (
                    <div key={uploadedFile.id} className="border rounded-lg p-4">
                      <div className="flex items-center justify-between mb-2">
                        <div className="flex items-center gap-3">
                          <FileText className="w-5 h-5 text-muted-foreground" />
                          <div>
                            <p className="font-medium text-sm">{uploadedFile.file.name}</p>
                            <p className="text-xs text-muted-foreground">
                              {(uploadedFile.file.size / 1024 / 1024).toFixed(2)} MB
                            </p>
                          </div>
                        </div>

                        <div className="flex items-center gap-2">
                          {uploadedFile.status === "success" && <CheckCircle className="w-5 h-5 text-green-500" />}
                          {uploadedFile.status === "error" && <AlertCircle className="w-5 h-5 text-destructive" />}
                          {uploadedFile.status === "ready" && (
                            <Button size="sm" onClick={() => handleIndividualSubmit(uploadedFile.id)}>
                              <Send className="w-4 h-4 mr-2" />
                              Process
                            </Button>
                          )}
                          <Button variant="ghost" size="sm" onClick={() => removeFile(uploadedFile.id)}>
                            <X className="w-4 h-4" />
                          </Button>
                        </div>
                      </div>

                      {uploadedFile.status === "uploading" && (
                        <div className="space-y-2">
                          <Progress value={uploadedFile.progress} className="h-2" />
                          <p className="text-xs text-muted-foreground">
                            Processing CV... {Math.round(uploadedFile.progress)}%
                          </p>
                        </div>
                      )}

                      {uploadedFile.status === "ready" && (
                        <Alert className="mt-2">
                          <Upload className="h-4 w-4" />
                          <AlertDescription>
                            CV ready to process. Click the Process button to analyze your CV.
                          </AlertDescription>
                        </Alert>
                      )}

                      {uploadedFile.status === "success" && (
                        <Alert className="mt-2">
                          <CheckCircle className="h-4 w-4" />
                          <AlertDescription>
                            CV processed successfully! Data extracted and ready for preview.
                          </AlertDescription>
                        </Alert>
                      )}

                      {uploadedFile.status === "error" && (
                        <Alert variant="destructive" className="mt-2">
                          <AlertCircle className="h-4 w-4" />
                          <AlertDescription>{uploadedFile.error || "Failed to process CV."}</AlertDescription>
                        </Alert>
                      )}
                    </div>
                  ))}
                </CardContent>
              </Card>
            )}
          </TabsContent>

          <TabsContent value="preview" className="space-y-6">
            {successfulFiles.map((uploadedFile) => (
              <Card key={uploadedFile.id}>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <CardTitle className="flex items-center gap-2">
                      <Eye className="w-5 h-5" />
                      CV Analysis Results - {uploadedFile.file.name}
                    </CardTitle>
                    <Button variant="outline" size="sm" onClick={() => downloadPreviewData(uploadedFile)}>
                      <Download className="w-4 h-4 mr-2" />
                      Download Report
                    </Button>
                  </div>
                </CardHeader>
                {/* <CardContent className="space-y-6">{renderParsedData(uploadedFile.parsedData)}</CardContent> */}
                <CardContent className="space-y-6">{uploadedFile.parsedData && renderParsedData(uploadedFile.parsedData)}</CardContent>

                
              </Card>
            ))}
          </TabsContent>

          <TabsContent value="analysis" className="space-y-6">
            <Card className="bg-slate-900 border-slate-800 text-slate-100">
              <CardHeader>
                <CardTitle>Real-time CV Analysis</CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                {successfulFiles.length > 0 ? (
                  <div className="space-y-6">
                    {successfulFiles.map((file) => (
                      <div key={file.id} className="border rounded-lg p-6">
                        <h3 className="text-xl font-semibold mb-4 flex items-center gap-2">
                          <FileText className="w-5 h-5" />
                          {file.file.name}
                        </h3>
                        {file.parsedData ? (
                          renderAnalysisSection(file.parsedData, file.file.name)
                        ) : (
                          <div className="text-center py-8 text-muted-foreground">
                            <AlertCircle className="w-8 h-8 mx-auto mb-2" />
                            No analysis data available for this CV.
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-12">
                    <Upload className="w-12 h-12 mx-auto mb-4 text-muted-foreground" />
                    <p className="text-muted-foreground text-lg">
                      Upload and process a CV to see real-time analysis results.
                    </p>
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  )
}